{
 "title": "k8s-☸-pgmon/node-exporter-Brief",
 "tags": [
  "节点利用率和饱和度",
  "主机状态监控"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "磁盘状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1-sum(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"}) by (instance,device) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (instance,device)"
    },
    {
     "expr": "max(node_filesystem_free_bytes) by (fstype)"
    },
    {
     "expr": "max(node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}) by (device,instance)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (device)  "
    }
   ]
  },
  {
   "title": "节点CPU利用量/5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!~\"^(?:guest.*)$\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "节点CPU饱和度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1) by (instance ) / count(node_cpu_seconds_total{mode=\"system\"}) by (instance ) * 100",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "节点内存利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "网络利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance) + sum(rate(node_network_transmit_bytes_total[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "网络饱和度",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total[5m])) by (instance) + sum(rate(node_network_transmit_drop_total[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}